In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("students(1).csv")

In [5]:
print(df)

   Student_ID   Name  Gender  Age  Math  Science  Marks
0         101   Ravi    Male   20    85       90     88
1         102  Priya  Female   21    78       82     80
2         103  Kumar    Male   22    92       88     90
3         104  Divya  Female   20    65       75     70
4         105   Arun    Male   23    80       85     82
5         106  Sneha  Female   21    88       91     89
6         107    Raj    Male   22    75       79     77
7         108  Meena  Female   20    90       94     92
8         109   Ajay    Male   24    72       70     71
9         110    Anu  Female   22    86       89     87

In [6]:
df.head()

   Student_ID   Name  Gender  Age  Math  Science  Marks
0         101   Ravi    Male   20    85       90     88
1         102  Priya  Female   21    78       82     80
2         103  Kumar    Male   22    92       88     90
3         104  Divya  Female   20    65       75     70
4         105   Arun    Male   23    80       85     82

In [7]:
df.shape

(10, 7)

In [8]:
print(df.dtypes)

Student_ID     int64
Name          object
Gender        object
Age            int64
Math           int64
Science        int64
Marks          int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Gender      10 non-null     object
 3   Age         10 non-null     int64
 4   Math        10 non-null     int64
 5   Science     10 non-null     int64
 6   Marks       10 non-null     int64
dtypes: int64(5), object(2)
memory usage: 688.0+ bytes

In [10]:
df.describe()

       Student_ID        Age       Math    Science      Marks
count    10.00000  10.000000  10.000000  10.000000  10.000000
mean    105.50000  21.500000  81.100000  84.300000  82.600000
std       3.02765   1.354006   8.659613   7.689098   7.919035
min     101.00000  20.000000  65.000000  70.000000  70.000000
25%     103.25000  20.250000  75.750000  79.750000  77.750000
50%     105.50000  21.500000  82.500000  86.500000  84.500000
75%     107.75000  22.000000  87.500000  89.750000  88.750000
max     110.00000  24.000000  92.000000  94.000000  92.000000

In [11]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Math', 'Science', 'Marks'], dtype='object')

In [12]:
for col in df.columns:
    print(col, df[col].dtype,df[col].nunique())

Student_ID int64 10
Name object 10
Gender object 2
Age int64 5
Math int64 10
Science int64 10
Marks int64 10

In [13]:
csvdata = pd.read_csv("students(1).csv")
exceldata =pd.read_excel("students.xlsx")
JSONdata = pd.read_json("students.json")

In [14]:
print(csvdata)
print(exceldata)
print(JSONdata)

merged = pd.concat([csvdata, exceldata, JSONdata], ignore_index=True)

print(merged)

   Student_ID   Name  Gender  Age  Math  Science  Marks
0         101   Ravi    Male   20    85       90     88
1         102  Priya  Female   21    78       82     80
2         103  Kumar    Male   22    92       88     90
3         104  Divya  Female   20    65       75     70
4         105   Arun    Male   23    80       85     82
5         106  Sneha  Female   21    88       91     89
6         107    Raj    Male   22    75       79     77
7         108  Meena  Female   20    90       94     92
8         109   Ajay    Male   24    72       70     71
9         110    Anu  Female   22    86       89     87
   Student_ID   Name  Gender  Age  Math  Science  Marks
0         101   Ravi    Male   20    85       90     88
1         102  Priya  Female   21    78       82     80
2         103  Kumar    Male   22    92       88     90
3         104  Divya  Female   20    65       75     70
4         105   Arun    Male   23    80       85     82
5         106  Sneha  Female   21    88       91     89
6         107    Raj    Male   22    75       79     77
7         108  Meena  Female   20    90       94     92
8         109   Ajay    Male   24    72       70     71
9         110    Anu  Female   22    86       89     87
   Student_ID   Name  Gender  Age  Math  Science  Marks
0         101   Ravi    Male   20    85       90     88
1         102  Priya  Female   21    78       82     80
2         103  Kumar    Male   22    92       88     90
3         104  Divya  Female   20    65       75     70
4         105   Arun    Male   23    80       85     82
5         106  Sneha  Female   21    88       91     89
6         107    Raj    Male   22    75       79     77
7         108  Meena  Female   20    90       94     92
8         109   Ajay    Male   24    72       70     71
9         110    Anu  Female   22    86       89     87
    Student_ID   Name  Gender  Age  Math  Science  Marks
0          101   Ravi    Male   20    85       90     88
1          102  Priya  Female   21    78       82     80
2          103  Kumar    Male   22    92       88     90
3          104  Divya  Female   20    65       75     70
4          105   Arun    Male   23    80       85     82
5          106  Sneha  Female   21    88       91     89
6          107    Raj    Male   22    75       79     77
7          108  Meena  Female   20    90       94     92
8          109   Ajay    Male   24    72       70     71
9          110    Anu  Female   22    86       89     87
10         101   Ravi    Male   20    85       90     88
11         102  Priya  Female   21    78       82     80
12         103  Kumar    Male   22    92       88     90
13         104  Divya  Female   20    65       75     70
14         105   Arun    Male   23    80       85     82
15         106  Sneha  Female   21    88       91     89
16         107    Raj    Male   22    75       79     77
17         108  Meena  Female   20    90       94     92
18         109   Ajay    Male   24    72       70     71
19         110    Anu  Female   22    86       89     87
20         101   Ravi    Male   20    85       90     88
21         102  Priya  Female   21    78       82     80
22         103  Kumar    Male   22    92       88     90
23         104  Divya  Female   20    65       75     70
24         105   Arun    Male   23    80       85     82
25         106  Sneha  Female   21    88       91     89
26         107    Raj    Male   22    75       79     77
27         108  Meena  Female   20    90       94     92
28         109   Ajay    Male   24    72       70     71
29         110    Anu  Female   22    86       89     87

In [15]:
print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Age           0
Math          0
Science       0
Marks         0
dtype: int64

In [16]:
print('total Missing:', df.isnull().sum().sum())

total Missing: 0

In [17]:
df['marks']=df['Marks'].fillna(df['Marks'].mean())
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [18]:
df =df.drop_duplicates()

In [19]:
df['Name'] = df['Name'].str.strip()

print(df.head())

   Student_ID   Name  Gender  Age  Math  Science  Marks  marks
0         101   Ravi    Male   20    85       90     88     88
1         102  Priya  Female   21    78       82     80     80
2         103  Kumar    Male   22    92       88     90     90
3         104  Divya  Female   20    65       75     70     70
4         105   Arun    Male   23    80       85     82     82

In [22]:
df['Total']= df['Math'] + df['Science']
print(df['Total'])

0    175
1    160
2    180
3    140
4    165
5    179
6    154
7    184
8    142
9    175
Name: Total, dtype: int64

In [23]:
print(df.head())

   Student_ID   Name  Gender  Age  Math  Science  Marks  marks  Total
0         101   Ravi    Male   20    85       90     88     88    175
1         102  Priya  Female   21    78       82     80     80    160
2         103  Kumar    Male   22    92       88     90     90    180
3         104  Divya  Female   20    65       75     70     70    140
4         105   Arun    Male   23    80       85     82     82    165